---
cirrus-ci_task:
  container:
    image: toxchat/toktok-stack:0.0.7
    cpu: 2
    memory: 2G
  configure_script:
    - /src/workspace/tools/inject-repo c-toxcore
  test_all_script:
    - bazel test -k
        --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST
        --config=ci
        --config=docker
        --config=release
        //c-toxcore/...
